apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello-yml
spec:
  replicas: 6
  selector:
    matchLabels:
      app: k8s-web-hello-yml
  template:
    metadata:
      labels:
        app: k8s-web-hello-yml
    spec:
      containers:
      - name: k8s-web-hello-yml
        image: tikkit/k8s-web-hello:3
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
